baseurl = "https://www.wangyuanyou.org"
title = "王石宝的博客"
theme = "hugo-universal-blog-theme"
themesDir = "../"
languageCode = "zh-cn"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "首页"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "技术博客"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "人生随笔"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "关于"
    url  = "/about/"
    weight = 4

[params]
    viewMorePostLink = "/blog/"
    author = "王石宝"
    defaultKeywords = ["王石宝", "blog"]
    defaultDescription = "王石宝的博客"

    #Â Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    copyright = "版权声明：自由转载-非商用-非衍生-保持署名（创意共享3.0许可证）"

    # Format dates with Go's time formatting，Go设定时间格式必须基于此时间原点
    date_format = "2006/01/02"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.recent_posts]
    enable = true
    title = "近期博客"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
